- name: Baixando e descompactando Wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/
    validate_certs: no
    remote_src: yes

- name: Criando Diretorios de site
  command: cp /var/www/wordpress {{apachedocroot}}/{{item.record}}.{{item.zone}} -rfv
  with_items: "{{apps}}"
  notify: Reiniciar Apache2

- name: Criando wp-config.php
  template:
    src: "wp-config.php.j2"
    dest: "{{apachedocroot}}/{{item.record}}.{{item.zone}}/wp-config.php"
  with_items: "{{apps}}"

- name: Limpando Dir
  file:
    path: /var/www/wordpress
    state: absent