- hosts: all
  become: yes
  user: ubuntu
  pre_tasks:
  - name: "Atualizando os Repos"
    raw: apt update
  - name: "Instalando o Python"
    raw: apt install python3 -y
  roles:
  - { role: default, tags: ["default_role"]}

- hosts: web
  become: yes
  user: ubuntu
  roles:
  - { role: web-server, tags: ["web-server_role"]}
  - { role: wordpress, tags: ["wordpress_role"]}

- hosts: database
  become: yes
  user: ubuntu
  roles:
  - { role: db-server, tags: ["db-server_role"]}  